version: '3.8'

volumes:
  db:
  
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./server
    privileged: true
    volumes:
      - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
      - /sys/class/gpio:/sys/class/gpio
      # https://stackoverflow.com/a/53626586
    environment:
      - DB_URL=value
      - JWT_SECRET=value
  
  client:
    container_name: client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:80
    depends_on:
      - server
  
  db:
    container_name: db
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db