version: '3.8'

volumes:
  letsencrypt:
  
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./server
    privileged: true
    volumes:
      - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
      - /sys/class/gpio:/sys/class/gpio
      # https://stackoverflow.com/a/53626586
    environment:
      - DB_URL=value
      - JWT_SECRET=value
      - REFRESH_SECRET=value
  
  client:
    container_name: client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        - CERTBOT_EMAIL=info@example.com
        - DOMAIN_LIST=example.com
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - server