version: '3.8'

volumes:
  data:
  le:

services:

  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - le:/etc/letsencrypt

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"