version: '3.8'
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
        - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
        - /sys/class/gpio:/sys/class/gpio
  client:
    container_name: client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - server