version: '3.8'

volumes:
  data:
  le:

services:

  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - le:/etc/letsencrypt

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio
      - /sys/class/gpio:/sys/class/gpio
    environment:
      - TOKEN_SECRET=value
      - REFRESH_TOKEN_SECRET=value
    ports:
      - "3001:3001"

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
